string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef token)
set(output "${TEST_DIR}/${token}/artifacts")
execute_process(COMMAND "${ASR_CLI}" dry-run --set "output.directory=${output}" --set audio.duration_ms=1250
  RESULT_VARIABLE code OUTPUT_VARIABLE payload ERROR_VARIABLE error)
if(NOT code EQUAL 0 OR EXISTS "${output}")
  message(FATAL_ERROR "dry-run failed or wrote artifacts: ${error}")
endif()
string(JSON chunks GET "${payload}" chunks)
if(NOT chunks EQUAL 7)
  message(FATAL_ERROR "dry-run omitted tail chunk")
endif()
execute_process(COMMAND "${ASR_CLI}" validate --set model.runtime=qwen_native --set model.path=/tmp/m3-not-loaded
  --set audio.realtime_pacing=true --set "output.directory=${output}"
  RESULT_VARIABLE code OUTPUT_VARIABLE payload ERROR_VARIABLE error)
if(EXISTS "${output}" OR (NATIVE_BUILD AND NOT code EQUAL 0) OR (NOT NATIVE_BUILD AND code EQUAL 0))
  message(FATAL_ERROR "native build capability/validation or no-artifact contract failed: ${error}")
endif()
execute_process(COMMAND "${ASR_CLI}" run --set "output.directory=${output}" --set audio.duration_ms=1250 --set dataset.language=id
  RESULT_VARIABLE code OUTPUT_VARIABLE payload ERROR_VARIABLE error)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "mock CLI run failed: ${error}")
endif()
string(JSON run_directory GET "${payload}" run_directory)
foreach(name IN ITEMS config.json environment.json events.jsonl audio_timing.jsonl status.json summary.json
    runtime_timing.jsonl system_metrics.jsonl calls.jsonl workers.jsonl errors.jsonl)
  if(NOT EXISTS "${run_directory}/${name}")
    message(FATAL_ERROR "missing ${name}")
  endif()
endforeach()
file(STRINGS "${run_directory}/audio_timing.jsonl" audio_lines)
list(LENGTH audio_lines audio_count)
if(NOT audio_count EQUAL 7)
  message(FATAL_ERROR "wrong persisted audio timing count")
endif()
file(READ "${run_directory}/config.json" resolved_config)
string(JSON effective_samples GET "${resolved_config}" audio effective_samples)
if(NOT effective_samples EQUAL 20000)
  message(FATAL_ERROR "effective audio length missing from resolved config")
endif()
file(READ "${run_directory}/status.json" status)
string(JSON state GET "${status}" status)
string(JSON mock GET "${status}" is_mock)
if(NOT state STREQUAL "COMPLETE" OR NOT mock)
  message(FATAL_ERROR "mock run not clearly marked complete")
endif()
file(READ "${run_directory}/summary.json" summary)
string(JSON elapsed GET "${summary}" elapsed_clock_ns)
string(JSON domain GET "${summary}" clock_domain)
string(JSON worker_id GET "${summary}" worker_id)
if(NOT elapsed EQUAL 1250000000 OR NOT domain STREQUAL "simulated")
  message(FATAL_ERROR "wrong simulated timeline")
endif()
if(NOT worker_id MATCHES "^worker_0_g1$")
  message(FATAL_ERROR "CLI did not use M5 managed worker")
endif()
file(STRINGS "${run_directory}/workers.jsonl" worker_lines)
list(LENGTH worker_lines worker_count)
if(NOT worker_count EQUAL 1)
  message(FATAL_ERROR "worker assignment artifact missing")
endif()
