# No network access at configure/build time. Bootstrap once using the fetch script.
find_package(Git REQUIRED)
foreach(dep IN ITEMS yaml-cpp json)
  if(dep STREQUAL "yaml-cpp")
    set(expected f7320141120f720aecc4c32be25586e7da9eb978)
  else()
    set(expected 9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03)
  endif()
  set(source "${PROJECT_SOURCE_DIR}/third_party/${dep}")
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" rev-parse HEAD
    OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
  if(NOT result EQUAL 0 OR NOT actual STREQUAL expected)
    message(FATAL_ERROR "Missing/wrong ${dep}; run bash scripts/fetch_foundation.sh")
  endif()
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" status --porcelain --untracked-files=no
    OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
  if(NOT result EQUAL 0 OR dirty)
    message(FATAL_ERROR "${dep} has unreviewed tracked edits")
  endif()
endforeach()
set(YAML_CPP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(YAML_CPP_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(YAML_CPP_INSTALL OFF CACHE BOOL "" FORCE)
set(YAML_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
set(JSON_Install OFF CACHE BOOL "" FORCE)
function(asr_add_foundation_dependencies)
  # Pinned releases declare older policy minima; permit them on CMake 4 without vendor edits.
  set(CMAKE_POLICY_VERSION_MINIMUM 3.10)
  add_subdirectory(third_party/yaml-cpp EXCLUDE_FROM_ALL)
  # yaml-cpp 0.8.0 relied on a transitive integer-types include removed by GCC 16.
  target_compile_options(yaml-cpp PRIVATE -include cstdint)
  add_subdirectory(third_party/json EXCLUDE_FROM_ALL)
endfunction()
asr_add_foundation_dependencies()
