if(ASR_ENABLE_QWEN_NATIVE)
  add_executable(native-worker-stub tests/integration/native_worker_stub.cpp)
  target_include_directories(native-worker-stub PRIVATE src/engines/native/src)
  target_link_libraries(native-worker-stub PRIVATE nlohmann_json::nlohmann_json asr_warnings)
  add_executable(native-adapter-test tests/integration/native_adapter_test.cpp)
  target_link_libraries(native-adapter-test PRIVATE asr_native asr_warnings)
  add_test(NAME native_adapter_contracts COMMAND native-adapter-test $<TARGET_FILE:native-worker-stub>)
  set_tests_properties(native_adapter_contracts PROPERTIES LABELS "integration;native-contract")
  add_executable(native-manager-test tests/integration/native_manager_test.cpp)
  target_link_libraries(native-manager-test PRIVATE asr_session_manager asr_native Threads::Threads asr_warnings)
  add_test(NAME native_manager_contracts COMMAND native-manager-test $<TARGET_FILE:native-worker-stub>)
  set_tests_properties(native_manager_contracts PROPERTIES LABELS "integration;native-contract")
  add_executable(prefix-scheduler-test tests/unit/prefix_scheduler_test.cpp)
  target_include_directories(prefix-scheduler-test PRIVATE src/engines/prefix/include)
  target_link_libraries(prefix-scheduler-test PRIVATE asr_warnings)
  add_test(NAME prefix_scheduler_contracts COMMAND prefix-scheduler-test)
  add_executable(prefix-worker-stub tests/integration/prefix_worker_stub.cpp)
  target_include_directories(prefix-worker-stub PRIVATE src/engines/prefix/src)
  target_link_libraries(prefix-worker-stub PRIVATE asr_prefix_multiplex nlohmann_json::nlohmann_json asr_warnings)
  add_executable(prefix-pool-test tests/integration/prefix_pool_test.cpp)
  target_link_libraries(prefix-pool-test PRIVATE asr_prefix_multiplex asr_warnings)
  add_test(NAME prefix_pool_contracts COMMAND prefix-pool-test $<TARGET_FILE:prefix-worker-stub>)
  set_tests_properties(prefix_scheduler_contracts prefix_pool_contracts PROPERTIES LABELS "model-free;prefix" TIMEOUT 30)
endif()
add_executable(measurement-test tests/unit/measurement_test.cpp)
target_link_libraries(measurement-test PRIVATE asr_observability asr_warnings)
add_test(NAME measurement_contracts COMMAND measurement-test)
set_tests_properties(measurement_contracts PROPERTIES LABELS "unit;model-free")
add_executable(session-manager-test tests/unit/session_manager_test.cpp)
target_link_libraries(session-manager-test PRIVATE asr_session_manager asr_mock asr_audio Threads::Threads asr_warnings)
add_test(NAME session_manager_contracts COMMAND session-manager-test)
set_tests_properties(session_manager_contracts PROPERTIES LABELS "unit;model-free")
add_executable(load-test tests/unit/load_test.cpp)
target_link_libraries(load-test PRIVATE asr_baseline asr_mock Threads::Threads asr_warnings)
add_test(NAME load_contracts COMMAND load-test)
set_tests_properties(load_contracts PROPERTIES LABELS "unit;model-free")
add_executable(sweep-test tests/unit/sweep_test.cpp)
target_link_libraries(sweep-test PRIVATE asr_baseline asr_mock Threads::Threads asr_warnings)
add_test(NAME sweep_contracts COMMAND sweep-test ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml)
set_tests_properties(sweep_contracts PROPERTIES LABELS "unit;model-free")
add_executable(websocket-test tests/integration/websocket_test.cpp)
target_link_libraries(websocket-test PRIVATE asr_baseline asr_websocket asr_mock Threads::Threads asr_warnings)
add_test(NAME websocket_contracts COMMAND websocket-test)
set_tests_properties(websocket_contracts PROPERTIES LABELS "integration;model-free;network")
add_executable(api-service-test tests/integration/api_service_test.cpp)
target_link_libraries(api-service-test PRIVATE asr_websocket asr_session_manager asr_mock Threads::Threads asr_warnings)
add_test(NAME api_service_contracts COMMAND api-service-test ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml)
set_tests_properties(api_service_contracts PROPERTIES LABELS "integration;model-free;network")
add_executable(chunk-schedule-test tests/unit/chunk_schedule_test.cpp)
target_link_libraries(chunk-schedule-test PRIVATE asr::core)
add_test(NAME chunk_schedule COMMAND chunk-schedule-test)
set_tests_properties(chunk_schedule PROPERTIES LABELS "unit;model-free")
add_executable(foundation-test tests/unit/foundation_test.cpp)
target_link_libraries(foundation-test PRIVATE asr_baseline asr_mock Threads::Threads asr_warnings)
add_test(NAME foundation_contracts COMMAND foundation-test)
set_tests_properties(foundation_contracts PROPERTIES LABELS "unit;model-free")
add_executable(audio-test tests/unit/audio_test.cpp)
target_link_libraries(audio-test PRIVATE asr_audio asr_mock asr_warnings)
add_test(NAME audio_contracts COMMAND audio-test)
set_tests_properties(audio_contracts PROPERTIES LABELS "unit;model-free")
add_executable(audio-realtime-60-test tests/integration/audio_realtime_60.cpp)
target_link_libraries(audio-realtime-60-test PRIVATE asr_audio asr_warnings)
add_test(NAME cli_validate COMMAND asr-cli validate --config ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml)
add_test(NAME cli_dry_run COMMAND asr-cli dry-run --config ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml --set dataset.language=zh)
add_test(NAME cli_load_dry_run COMMAND asr-cli load-dry-run
  --config ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml
  --set audio.realtime_pacing=true --set workers.processes=2
  --calls 3 --concurrency 2 --languages en,id,zh)
add_test(NAME cli_manifest_without_base COMMAND asr-cli load
  --config ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml
  --manifest ${PROJECT_SOURCE_DIR}/tests/fixtures/load_manifest.jsonl
  --set audio.source=wav --set audio.path=missing_manifest_base.wav
  --set audio.realtime_pacing=true --concurrency 1
  --set output.directory=${CMAKE_BINARY_DIR}/manifest-tests)
set_tests_properties(cli_manifest_without_base PROPERTIES LABELS "integration;model-free")
add_test(NAME cli_sweep_dry_run COMMAND asr-cli sweep-dry-run
  --config ${PROJECT_SOURCE_DIR}/configs/mock_baseline.yaml
  --set audio.realtime_pacing=true --preset chunks --calls 2 --concurrency 1)
set_tests_properties(cli_validate cli_dry_run cli_load_dry_run cli_sweep_dry_run
  PROPERTIES LABELS "integration;model-free")
add_test(NAME cli_artifacts COMMAND ${CMAKE_COMMAND}
  -DASR_CLI=$<TARGET_FILE:asr-cli> -DTEST_DIR=${CMAKE_BINARY_DIR}/cli-tests
  -DNATIVE_BUILD=${ASR_ENABLE_QWEN_NATIVE}
  -P ${PROJECT_SOURCE_DIR}/tests/integration/cli_contract.cmake)
set_tests_properties(cli_artifacts PROPERTIES LABELS "integration;model-free")
